const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Behaviors.Platform,
		C3.Plugins.Spritefont2,
		C3.Behaviors.solid,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Mouse.Cnds.OnObjectClicked
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{Teclado: 0},
	{Mouse: 0},
	{Áudio: 0},
	{Start: 0},
	{FundoFase1: 0},
	{Plataforma: 0},
	{Personagem: 0},
	{GameOver: 0},
	{Yes: 0},
	{No: 0},
	{Vida: 0},
	{CliqueEm: 0},
	{PlayAgain: 0},
	{Direcao: 0},
	{Inimigo1: 0},
	{Sólido: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{colisão: 0},
	{colisão2: 0},
	{txtVida: 0},
	{Moeda: 0},
	{colisão4: 0},
	{Inimigo2: 0},
	{Sprite2: 0},
	{Portal: 0},
	{Nome: 0},
	{colisão6: 0},
	{Sprite7: 0},
	{finalBackground: 0},
	{FonteDeSprites: 0},
	{Finalbutton: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite8: 0},
	{vidas: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Áudio: class extends self.IInstance {},
	Start: class extends self.ISpriteInstance {},
	FundoFase1: class extends self.ISpriteInstance {},
	Personagem: class extends self.ISpriteInstance {},
	GameOver: class extends self.ISpriteFontInstance {},
	Yes: class extends self.ISpriteFontInstance {},
	No: class extends self.ISpriteFontInstance {},
	Vida: class extends self.ISpriteInstance {},
	CliqueEm: class extends self.ISpriteFontInstance {},
	PlayAgain: class extends self.ISpriteFontInstance {},
	Inimigo1: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	colisão: class extends self.ISpriteInstance {},
	colisão2: class extends self.ISpriteInstance {},
	txtVida: class extends self.ISpriteFontInstance {},
	Moeda: class extends self.ISpriteInstance {},
	colisão4: class extends self.ISpriteInstance {},
	Inimigo2: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Portal: class extends self.ISpriteInstance {},
	Nome: class extends self.ISpriteInstance {},
	colisão6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	finalBackground: class extends self.ISpriteInstance {},
	FonteDeSprites: class extends self.ISpriteFontInstance {},
	Finalbutton: class extends self.ISpriteFontInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {}
}